keywords: >-
  edmonton, breakdance, practice, session, bboy, bgirl, breakdancer, break,
  dance, hiphop, hip hop, yeg, choreography, freestyle, movement, art, culture

email: info@freestylemovement.ca
url: https://freestylemovement.ca
plugins:
  - jekyll-sitemap


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
