email: info@freestylemovement.ca
description: >-
    Freestyle Movement is your go to for Edmonton Break Dance events, classes, and practice spots.
  
url: "https://freestylemovement.ca"


plugins:
  - jekyll-sitemap