baseURL = "https://freestylemovement.ca"
languageCode = "en-us"
title = "Freestyle Movement"
theme = "fm-theme"
removePathAccents = true



# HTML before the closing </head>
[params]
customHead = ""



# Navigation
[params.navigation]
logo = "images/siteicon.png"
home = "Home"
about = "About"
styles = "Styles"
movevents = "Movevents"
contact = "Contact Us"



# Main
[params.main]
enable            = true
bg                = "images/practice-header.jpg"
title             = "FREESTYLE MOVEMENT"
subtitle          = "We create opportunities for bboys, bgirls, choreographers and freestyle dancers to grow and build the Hip Hop community in Edmonton. We teach classes, organize competitions and run a weekly open practice session (Change this)"
btnText           = "Learn More"



# Info
[params.info]
enable      = true
heading     = ""
description = ""

[[params.info.sliderItem]]
image   = "images/about/fm-logo-p.jpg"
[[params.info.sliderItem]]
image   = "images/about/unrivaled.jpg"
[[params.info.sliderItem]]
image   = "images/about/unrivaled.jpg"
[[params.info.sliderItem]]
image   = "/images/about/prac-1.jpg"
[[params.info.sliderItem]]
image   = "/images/about/prac-2.jpg"



# About
[params.about]
enable      = true
heading     = "Header"
description = "Some more stuff"

[[params.about.sliderItem]]
image   = "images/about/fm-logo-p.jpg"
[[params.about.sliderItem]]
image   = "images/about/unrivaled.jpg"
[[params.about.sliderItem]]
image   = "images/about/unrivaled.jpg"
[[params.about.sliderItem]]
image   = "/images/about/prac-1.jpg"
[[params.about.sliderItem]]
image   = "/images/about/prac-2.jpg"



# Styles
[params.styles]
enable      = true
title       = "Dance Styles"
subtitle    = "Here we can put all the different dance styles"

[[params.styles.stylesItem]]
# use delay for reveal items one by one
icon    = ""
title   = "[Breakdancin]()"
description = ""
delay   = "0s"

[[params.styles.stylesItem]]
icon    = ""
title   = "[Locking]()"
description = ""
delay   = "0.2s"

[[params.styles.stylesItem]]
icon    = ""
title   = "[Whacking]()"
description = ""
delay   = "0.4s"

[[params.styles.stylesItem]]
icon    = ""
title   = "[K-Pop]()"
description = ""

delay   = "0.6s"

[[params.styles.stylesItem]]
icon    = ""
title   = "[Contemporary]()"
description = ""
delay   = "0.8s"

[[params.styles.stylesItem]]
icon    = ""
title   = "[Popping]()"
description = ""
delay   = "1s"

[[params.styles.stylesItem]]
icon    = ""
title   = "[Tutting]()"
description = ""
delay   = "1.2s"

[[params.styles.stylesItem]]
icon    = ""
title   = "[Funk]()"
description = ""
delay   = "1.5s"



# Movevents
[params.movevents]
enable      = true
bg          = "images/movevents.jpg"
title       = "MOVEVENTS"
subtitle    = "List of our events goes here"



# Contact
[params.contact]
enable      = true
title       = "Contact Us"
subtitle    = "Some message about getting back to them ASAP"