baseURL = "http://freestylemovement.ca/"
languageCode = "en-us"
title = "Freestyle Movement"
theme = "fm-theme"

[markup]

    [markup.goldmark]

        [markup.goldmark.renderer]
        unsafe = true