name = "FM-Theme"
license = "MIT"
licenselink = ""
description = "Hugo port of Freestyle Movement's Template"
homepage = ""
tags = ['wonseok-han', 'hugo-theme', 'hugo-templates', 'bootstrap4']
features = ['bootstrap4','responsive']
min_version = "0.64.0"

[author]
  name = "Wonseok Han"
  homepage = "https://github.com/WonHan7/wonseok-portfolio"
